#!/usr/bin/env bash

package() {
  prefix="$1"
  [[ "$prefix" == "" ]] && echo "ERROR: USAGE is ./ake package <prefix>" && exit 1
  mkdir -p "$prefix/usr/bin"
  #mkdir -p "$prefix/usr/lib/systemd"
  mkdir -p "$prefix/usr/share/gutdeb"
  cp -r bin libexec "$prefix/usr/share/gutdeb"
  #cp misc/*.{service,timer} "$pkgdir/usr/lib/systemd/system"
  ln -s "/usr/share/gutdeb/bin/gutdeb" "$prefix/usr/bin"
}

case "$1" in
  p | package ) shift; package "$@" ;;
esac
