#!/usr/bin/env bash
#
# USAGE:
#
#   ./ake package archlinux "$pkgdir"
#

package() {
  distribution=$1; prefix="$2"
  [[ "$prefix" == "" ]] && echo "ERROR: USAGE is ./ake package <distribution> <prefix>" && exit 1
  case "$distribution" in
    ubuntu ) lib="lib" ;;
    * ) lib="usr/lib" ;;
  esac

  mkdir -p "$prefix/usr/bin"
  mkdir -p "$prefix/usr/share/gutdeb"
  cp -r bin libexec VERSION "$prefix/usr/share/gutdeb"
  ln -s "/usr/share/gutdeb/bin/gutdeb" "$prefix/usr/bin"
}

case "$1" in
  p | package ) shift; package "$@" ;;
esac
