#!/bin/bash

VERSION=$(dpkg-parsechangelog -ldebian/changelog | sed -rne 's,^Version: ([^-]+).*,\1,p')

[[ -e "../xware_${VERSION}.orig.tar.gz" ]] && exit

mkdir tmp/xware -p
unzip -q ../Xware${VERSION}_armel_v5te_glibc.zip -d tmp/xware/armhf
unzip -q ../Xware${VERSION}_x86_32_glibc.zip -d tmp/xware/i386
tar -C tmp -zcvf ../xware_${VERSION}.orig.tar.gz xware
rm -r tmp
