#!/usr/bin/env bash
#
# Summary: Build the source package
#
# Usage: gutdeb source
#
# Invoke debuild -S

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  debuild -S
}

main "$@"
