#!/usr/bin/env bash
#
# Summary: Remove ../package-version* ../*.tar.gz
#
# Usage: gutdeb clean

set -e
[ -n "$APP_DEBUG" ] && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  package=$(get_package)
  version=$(get_version)
  rm -rf ../${package}?${version}* ../*.tar.gz
}

main "$@"
