#!/usr/bin/env bash
#
# Summary: Publish deb package
#
# Usage: gutaur publish [version]
#
# Invokes clean -> version -> build -> upload

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  version="$1"

  app-clean
  if [[ $version != "" ]]; then
    app-version $version
  fi
  app-build
  app-upload
}

main "$@"
