#!/usr/bin/env bash
#
# Summary: Build the package
#
# Usage: gutdeb build
#
# Invoke debuild -b

set -e
[ -n "$APP_DEBUG" ] && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  package=$(get_package)
  version=$(get_version)

  # download upstream tarball and extract it.
  uscan --force-download

  tar xf "../${package}_${version}.orig.tar.gz" -C ..
  cd "../$package-$version"
  ln -s "../$package/debian" .

  debuild -b
}

main "$@"
