#!/usr/bin/env bash
#
# Summary: Remove ../package-version* ../*.tar.gz
#
# Usage: gutdeb clean

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  package=$(get_package)
  version=$(get_version)
  rm -rf debian/$package ../${package}?${version}* ../*.tar.gz
}

main "$@"
