#!/usr/bin/env bash
#
# Summary: Build the package
#
# Usage: gutdeb build
#
# Invoke debuild -b

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  package=$(get_package)
  version=$(get_version)
echo 1, $package, $version

  # download upstream tarball and extract it.
  uscan --force-download

  tar xf "../${package}_${version}.orig.tar.gz" -C ..
  ln -sf  "$(pwd)/debian" "../${package}-${version}"
  cd "../${package}-${version}"

  debuild -b
}

main "$@"
